services:
  - type: web
    name: cfo-agenda-creator-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://cfo-agenda-creator.herokuapp.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
